export enum CrosschainEvent {
  CrosschainRequestCreated = 'routerprotocol.routerchain.crosschain.EventCrosschainRequestCreated',
  CrosschainRequestConfirm = 'routerprotocol.routerchain.crosschain.EventCrosschainRequestConfirm',
  CrosschainReadyToExecute = 'routerprotocol.routerchain.crosschain.EventCrosschainReadyToExecute',
  CrosschainExecuted = 'routerprotocol.routerchain.crosschain.EventCrosschainExecuted',
  CrosschainAckRequestCreated = 'routerprotocol.routerchain.crosschain.EventCrosschainAckRequestCreated',
  CrosschainAckRequestConfirm = 'routerprotocol.routerchain.crosschain.EventCrosschainAckRequestConfirm',
  CrosschainAckReadyToExecute = 'routerprotocol.routerchain.crosschain.EventCrosschainAckReadyToExecute',
  CrosschainAckExecuted = 'routerprotocol.routerchain.crosschain.EventCrosschainAckExecuted',
  CrosschainAckReceiptCreated = 'routerprotocol.routerchain.crosschain.EventCrosschainAckReceiptCreated',
  CrosschainRequestCompleted = 'routerprotocol.routerchain.crosschain.EventCrosschainRequestCompleted',
  CrosschainAckCompleted = 'routerprotocol.routerchain.crosschain.EventCrosschainAckCompleted',
  CrosschainReceiptCompleted = 'routerprotocol.routerchain.crosschain.EventCrosschainReceiptCompleted',
  CrosschainRequestFeeSettlement = 'routerprotocol.routerchain.crosschain.EventCrosschainRequestFeeSettlement',
  CrosschainAckFeeSettlement = 'routerprotocol.routerchain.crosschain.EventCrosschainAckFeeSettlement',
  HandleNativeTransfer = 'routerprotocol.routerchain.crosschain.EventHandleNativeTransfer',
  CrosschainExecutionFailed = 'routerprotocol.routerchain.crosschain.EventCrosschainExecutionFailed',
  CrosschainAckExecutionFailed = 'routerprotocol.routerchain.crosschain.EventCrosschainAckExecutionFailed',
  AttestationVote = 'routerprotocol.routerchain.attestation.EventAttestationVote',
  AttestationObserved = 'routerprotocol.routerchain.attestation.EventAttestationObserved',
}
